# Generated by Django 2.0 on 2017-12-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='password',
            field=models.CharField(default=0, max_length=554),
            preserve_default=False,
        ),
    ]
