# Generated by Django 2.0 on 2018-01-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userform_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='surname',
            field=models.CharField(default='surname', max_length=254),
        ),
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(default='username', max_length=154),
        ),
    ]
