# Generated by Django 2.0 on 2018-01-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180102_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='surname',
            field=models.CharField(db_column='surname', default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(db_column='username', default='', max_length=154),
        ),
    ]
