# Generated by Django 2.0 on 2018-01-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180102_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password2',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
