# Generated by Django 2.0 on 2018-01-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password2',
        ),
    ]
