# Generated by Django 2.0 on 2018-01-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180102_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileing',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileing',
        ),
    ]
