# Generated by Django 2.0 on 2018-01-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180102_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='email',
            field=models.EmailField(db_column='email', max_length=354),
        ),
        migrations.AlterField(
            model_name='userform',
            name='password',
            field=models.CharField(db_column='password', max_length=554),
        ),
    ]
