# Generated by Django 2.0 on 2018-01-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180102_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
