# Generated by Django 2.0 on 2018-01-02 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(db_column='active', default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='barcode',
            field=models.BooleanField(db_column='barcode', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='email', default='abs@mail.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(db_column='staff', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='superuser',
            field=models.BooleanField(db_column='superuser', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, db_column='surname', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='username', default='', max_length=154),
        ),
    ]
