# Generated by Django 2.0 on 2018-01-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180102_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_column='date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(db_column='surname', default='Surname', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='username', default='Name', max_length=154),
        ),
    ]
