# Generated by Django 2.0 on 2018-01-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180103_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='surname',
            field=models.CharField(db_column='surname', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(db_column='username', max_length=154),
        ),
    ]
